import{a as b,S,i}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const q="52610822-f7e96d61057c97541c6e10504",w="https://pixabay.com/api/";async function u(e,o){const n={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await b.get(w,{params:n})).data}const m=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more");const v=new S(".gallery a",{captionsData:"alt",captionDelay:250});function f(e){const o=e.map(({webformatURL:n,largeImageURL:a,tags:t,likes:r,views:s,comments:g,downloads:L})=>`
      <a class="gallery-item" href="${a}">
        <img src="${n}" alt="${t}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${g}</p>
          <p><b>Downloads:</b> ${L}</p>
        </div>
      </a>
    `).join("");m.insertAdjacentHTML("beforeend",o),v.refresh()}function B(){m.innerHTML=""}function y(){const e=document.querySelector(".loader");e.classList.remove("hidden"),e.textContent="Loading images, please wait..."}function p(){const e=document.querySelector(".loader");e.classList.add("hidden"),e.textContent=""}function M(){document.querySelector(".load-more").classList.remove("hidden")}function d(){document.querySelector(".load-more").classList.add("hidden")}const E=document.querySelector(".search-form"),P=document.querySelector("input[name='query']"),$=document.querySelector(".load-more");let l="",c=1,h=0;E.addEventListener("submit",x);$.addEventListener("click",H);async function x(e){if(e.preventDefault(),l=P.value.trim(),!l){i.warning({message:"Please enter a search term!"});return}c=1,B(),d(),y();try{const o=await u(l,c);if(h=o.totalHits,o.hits.length===0){i.error({message:"No images found. Try another search!"});return}f(o.hits),o.totalHits>15&&M()}catch{i.error({message:"Something went wrong. Please try again."})}finally{p()}}async function H(){c+=1,y(),d();try{const e=await u(l,c);f(e.hits),O(),c*15>=h&&(d(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({message:"Error loading more images."})}finally{p()}}function O(){const e=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
